---
title: "FLAVOUR"
author: "Suhyeon Kwon"
format: 
  revealjs:
    footer: "FFR vs IVUS"
    smaller: true
    scrollable: true
    transition: slide
    slide-number: true
editor: visual
---

## Overview

-   관상동맥 질환(CAD)을 진단하고, 경피적 관상동맥 중재술(PCI) 여부를 결정하기 위해 관상동맥조영술(coronary angiography)을 이용하나, 추가 정보를 얻기 위해 IVUS와 FFR을 이용하기도 함

-   그러나 임상 결과와 관련하여 IVUS와 FFR의 차이에 관한 데이터가 부족함. 따라서 이 논문에서는 **IVUS와 FFR의 임상 결과를 비교**하고자 함

-   초기 목표는 FFR이 IVUS보다 우수하다는 것을 증명하는 것이었음. 그러나 약물 방출 스텐트 사용시 IVUS의 임상 결과를 개선할 수 있다는 연구 결과로 인해, IVUS에 대한 FFR의 비열등성(Noninferiority)을 평가하는 것으로 목표를 수정함

-   FFR이 더 적은 스텐트 배치와 더 적은 의료 자원의 소비로 이어질 것으로 예상된다는 점을 고려할 때, FFR의 비열등성을 증명하는 본 연구는 정당화될 수 있음

# Methods

## Population and Randomization

-   한국과 중국의 18개 기관에서 수행됨

-   허혈성 심장질환이 의심되고, 중간 협착증을 가지고 있는 19세 이상의 환자들을 대상으로 함

-   noncardiac coexisting illness을 가지고 있거나, 기대 여명이 2년 이하인 경우 제외함

-   실험에 참여한 환자들은 1:1 비율로 FFR 그룹과 IVUS 그룹에 무작위 배정됨

-   실험 기관과 당뇨병 유무에 따라 층화 추출함

## Outcomes and Definitions

-   primary outcome: 사망, 심근경색, 연구 기간 동안 혈관재형성(revascularization)

-   key secondary outcome: 환자별, 혈관별로 배치된 스텐트 개수, 뇌졸중 등

## Sample size

-   가정: 24개월 내 primary outcome의 발생률이 FFR 그룹에서 10%, IVUS 그룹에서 12%이다.

-   귀무가설(H0): FFR 그룹과 IVUS 그룹의 primary outcome 발생률 차이가 2.5%(noninferiority margin)이다. = FFR 그룹이 IVUS 그룹에 대해 열등하다.

-   sample size: 1700

-   검정력(power): 0.9 (90%)

-   type 1 error rate: 0.05 (5%)

-   단측검정 + 95% 신뢰구간 이용

-   **수식첨부**

## Statistical analysis

1.  Cox proportional-hazards model: 실험 장소와 당뇨병 유무에 따라 primary outcome 발생률 분석
    -   proportional-hazards model의 가정은 scaled된 Schoenfeld residuals 양측 검정으로 평가
2.  Kaplan-Meier: 첫 사건이 발생하기까지의 시간 분석
3.  모든 결과는 intention-to-treat&per-protocol / per-patient&per-vessel에 따라 분석
4.  결측치나 부적절한 데이터는 제거

# Results

## Patients and follow-up

-   총 1682명의 환자를 FFR 그룹(838명)과 IVUS 그룹(844명)으로 무작위 배정함

-   환자들의 평균 나이는 65세이며, 554명의 환자(32.9%)가 당뇨병을 가지고 있음

-   target vessel은 61.9%의 환자에서 좌전하행관상동맥이었으며, 두 그룹에서의 병변 길이, 기준 혈관의 직경, 표적 병변의 협착 직경은 유사함

-   **테이블2 첨부**

-   PCI를 받은 환자는 **IVUS 그룹(65.3%)**에서 FFR 그룹(44.4%)보다 더 많았음

    -   전체 스텐트 개수와 길이는 두 그룹에서 유사함

-   per-vessel 분석에서는, PCI의 빈도가 IVUS 그룹이 FFR 그룹보다 높았음

-   테이블 S3 첨부

-   환자 중 19명은 측정 실패, 44명은 프로토콜 위반

```         
-   11명: revascularization 기준을 만족하지 않는 병변에 PCI 수행

-   28명: revascularization 기준을 만족했으나 PCI 연기

-   5명: 약물 방출 스텐트를 사용하지 않고 PCI 수행
```

## Primary outcome

-   99.2%의 환자들에 대해 추적 관찰 완료, 14명 실패

-   연구 기간동안 primary outcome은 FFR 그룹에서 67명(8.1%), IVUS 그룹에서 71명(8.5%)에게 발생함

    -   95% 단측 신뢰구간: 1.8%p

    -   97.5% 단측 신뢰구간: 2.2%p

    -   P=0.01

-   테이블3 첨부

-   Schoenfeld residuals 검증의 통계량이 유의하지 않으므로 proportional-hazards model의 가정은 위배되지 않음

-   primary outcome 발생에 대한 hazard ratio는 0.96

    -   95% 단측 신뢰구간: 1.27

    -   97.5% 단측 신뢰구간: 1.35

## Secondary and other outcomes

-   secondary outcomes의 발생은 두 그룹에서 유사하며, 당뇨병 유무와 intention-to-treat&per-protocol 분석에서도 유사함

-   52.9%의 환자에서 PCI가 성공했으며, FFR 그룹(50.1%)과 IVUS 그룹(54.8%)에서도 유사한 수치를 보임

## Discussion

::: panel-tabset
### Conclusion

-   primary outcome 측면에서 FFR이 IVUS에 대해 비열등함

    -   IVUS 그룹보다 FFR 그룹에서 target-vessel PCI가 더 적게 수행되었고, 이는 더 적은 스텐트 배치와 더 적은 이중 항혈소판제 투여로 이어질 수 있음

### Limits

-   low-risk 환자를 대상으로 실험을 진행하여 high-risk 환자들에 적용이 어려움

-   수술 의사들은 지정된 그룹에 대해 알고 있었음

-   revascularization 빈도는 PCI 기준에 따라 다름

-   아시아인에 한해 연구가 진행됨
:::
